name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling the git repo
        uses: actions/checkout@v6
      - name: Installing python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: update pip3
        run: python3 -m pip install --upgrade pip
      - name: Installing Dependencies
        run: pip3 install -r requirements.txt
      - name: Testing with pytest
        run: |
          pip install pytest
          pytest
